### ISSUE TITLE
Transaction logger

### ISSUE THREAD

**Issue by JackGit** [ShawnXiao105/iotanet#5]
Node.js backend accepts transaction logs from device, and emits logs to frontend by socket
Frontend shows the live transaction logs from socket.

**Comment by lunkaleung** [comment]
Please comment the below example data that will send to Node.js backend. Thank you.

1. send car first connection event
{
    "device_id": "123",
    "device_type": "car",
    "connect_to": "456", 
    "connection_status": "success"
}

2. charger send auth message event 
{
    "device_id": "456",
    "device_type": "charger",
    "auth_device_id": "123",
    "auth_status": true
}

3. car send auth message event
{
    "device_id": "123",
    "device_type": "car",
    "auth_device_id": "456",
    "auth_status": true
}

4. car send balance is enough event
{
    "device_id": "123",
    "device_type": "car",
    "balance_status": true
}

5. car send transaction is done event
{
    "device_id": "123",
    "device_type": "car",
    "transaction_status": true
}

6. charger send valid transaction event
{
    "device_id": "456",
    "device_type": "charger",
    "transaction_status": true
}

7. charger send charging event
{
    "device_id": "456",
    "device_type": "charger",
    "charging_status": true
}

8. car send charging event
{
    "device_id": "123",
    "device_type": "car",
    "charging_status": true
}
